name: grocerlytics
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  auto_route: ^9.2.2
  collection: ^1.19.0
  dio: ^5.7.0
  equatable: ^2.0.7
  fl_chart: ^0.70.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  font_awesome_flutter: ^10.8.0
  get_it: ^8.0.3
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  injectable: ^2.5.0
  lottie: ^3.3.0
  mime: ^2.0.0
  path: ^1.9.0
  plausible_analytics: ^0.3.0
  scrollable_positioned_list: ^0.3.8
  shadcn_ui: ^0.17.2
  shared_preferences: ^2.3.4
  shimmer: ^3.0.0
  sqflite: ^2.4.1
  url_launcher: ^6.3.1
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  auto_route_generator: ^9.0.0
  injectable_generator: ^2.6.2

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/analyze_receipt.json
    - assets/app_icon_ios.svg
    - assets/app_icon.svg
    - pubspec.yaml
